---
variables:
  DOCKER_IMAGE_NAME: lansible/upx

include:
  - template: Container-Scanning.gitlab-ci.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/develop/default.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/develop/docker-build.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/develop/sast-cis-benchmark.yml

test:
  stage: test
  tags:
    - docker
  variables:
    DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}
    DOCKER_IMAGE_TAG: ${CI_COMMIT_SHA}
  script:
    - docker run ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}-amd64
  except:
    - tags
